"""
Landing / Home page for Sportalytics.

A marketing-style page similar to wisesportsai.com that showcases the
platform's features, sports coverage, and pricing plans.
"""

import dash
import dash_mantine_components as dmc
from dash import html
from dash_iconify import DashIconify

dash.register_page(
    __name__,
    path="/",
    title="Sportalytics — AI-Powered Sports Analytics",
    name="Home",
)

# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------

SPORTS = [
    ("mdi:football", "NFL"),
    ("mdi:basketball", "NBA"),
    ("mdi:baseball", "MLB"),
    ("mdi:hockey-puck", "NHL"),
    ("mdi:boxing-glove", "UFC"),
    ("mdi:football", "CFB"),
    ("mdi:basketball", "CBB"),
]

FEATURES = [
    {
        "icon": "mdi:robot-outline",
        "title": "AI Predictions",
        "desc": "50+ daily picks generated by ML models trained on years of historical data across all major sports.",
    },
    {
        "icon": "mdi:basketball",
        "title": "Player Props",
        "desc": "AI-graded over/under player prop predictions with historical hit rates and edge analysis.",
    },
    {
        "icon": "mdi:chart-line",
        "title": "Model Tracker",
        "desc": "Full transparency on model performance — ROI by sport, confidence tier, and monthly breakdowns.",
    },
    {
        "icon": "mdi:chart-areaspline",
        "title": "Odds Insight",
        "desc": "Real-time odds comparison across multiple sportsbooks to always find the best available line.",
    },
    {
        "icon": "mdi:lightning-bolt",
        "title": "Live Totals",
        "desc": "In-game pace tracking and projected total overlays for live betting decisions.",
    },
    {
        "icon": "mdi:calculator-variant-outline",
        "title": "Calculators",
        "desc": "Arbitrage, expected value, and odds conversion tools to maximize your edge.",
    },
]

HOW_IT_WORKS = [
    {
        "step": "01",
        "title": "Data Ingestion",
        "desc": "Our system ingests thousands of data points per day — historical results, injuries, weather, line movement, and more.",
    },
    {
        "step": "02",
        "title": "Model Analysis",
        "desc": "Ensemble ML models assign confidence scores, edges, and hit-rate projections to every game.",
    },
    {
        "step": "03",
        "title": "You Win More",
        "desc": "Get clear, actionable picks every morning with full rationale so you understand the edge.",
    },
]


def _stat_pill(value: str, label: str) -> dmc.Stack:
    return dmc.Stack(
        align="center",
        gap=2,
        children=[
            dmc.Text(value, size="xl", fw=800, c="green"),
            dmc.Text(label, size="xs", c="dimmed"),
        ],
    )


def hero_section() -> dmc.Paper:
    return dmc.Paper(
        radius=0,
        style={
            "background": "linear-gradient(160deg, #0a1a0a 0%, #0a0a0a 55%, #0a0f1a 100%)",
            "minHeight": "88vh",
            "display": "flex",
            "alignItems": "center",
        },
        children=dmc.Container(
            size="lg",
            py="xl",
            children=dmc.Stack(
                align="center",
                gap="lg",
                children=[
                    dmc.Badge(
                        [DashIconify(icon="mdi:robot-outline", width=16), " AI-Powered Sports Intelligence"],
                        color="green",
                        variant="light",
                        size="lg",
                        radius="xl",
                    ),
                    dmc.Title(
                        children=[
                            "Win More With ",
                            html.Span("AI", style={"color": "#51cf66"}),
                            " Sports Predictions",
                        ],
                        order=1,
                        ta="center",
                        style={"fontSize": "3rem", "lineHeight": "1.15", "maxWidth": 750},
                    ),
                    dmc.Text(
                        "Advanced machine learning models analyze thousands of data points "
                        "to deliver accurate, data-driven sports predictions across all major sports.",
                        ta="center",
                        c="dimmed",
                        size="lg",
                        maw=640,
                    ),
                    dmc.Group(
                        gap="md",
                        justify="center",
                        children=[
                            dmc.Anchor(
                                href="/free-pick",
                                style={"textDecoration": "none"},
                                children=dmc.Button(
                                    "Get Free Pick",
                                    size="lg",
                                    color="green",
                                    radius="md",
                                    leftSection=DashIconify(icon="mdi:gift-outline", width=16),
                                ),
                            ),
                            dmc.Anchor(
                                href="/predictions",
                                style={"textDecoration": "none"},
                                children=dmc.Button(
                                    "View AI Predictions →",
                                    size="lg",
                                    variant="outline",
                                    color="green",
                                    radius="md",
                                ),
                            ),
                        ],
                    ),
                    # Stats pills
                    dmc.Paper(
                        withBorder=True,
                        radius="xl",
                        px="xl",
                        py="md",
                        mt="md",
                        children=dmc.Group(
                            gap="xl",
                            justify="center",
                            wrap="wrap",
                            children=[
                                _stat_pill("53.6%", "Win Rate"),
                                dmc.Divider(orientation="vertical", h=40),
                                _stat_pill("50+", "Daily Picks"),
                                dmc.Divider(orientation="vertical", h=40),
                                _stat_pill("7", "Sports Covered"),
                                dmc.Divider(orientation="vertical", h=40),
                                _stat_pill("+1.67u", "Avg Units / Pick"),
                            ],
                        ),
                    ),
                ],
            ),
        ),
    )


def sports_section() -> dmc.Container:
    return dmc.Container(
        size="lg",
        py="xl",
        children=dmc.Stack(
            align="center",
            gap="lg",
            children=[
                dmc.Title("All Major Sports Covered", order=2, ta="center"),
                dmc.Text(
                    "Our models cover every major league and competition.",
                    c="dimmed",
                    ta="center",
                ),
                dmc.Group(
                    justify="center",
                    gap="md",
                    children=[
                        dmc.Card(
                            withBorder=True,
                            radius="md",
                            p="md",
                            style={"minWidth": 90, "textAlign": "center"},
                            children=[
                                DashIconify(icon=icon, width=26),
                                dmc.Text(sport, fw=600, size="sm", mt=4),
                            ],
                        )
                        for icon, sport in SPORTS
                    ],
                ),
            ],
        ),
    )


def features_section() -> dmc.Container:
    return dmc.Container(
        size="lg",
        py="xl",
        children=dmc.Stack(
            gap="xl",
            children=[
                dmc.Stack(
                    align="center",
                    gap="sm",
                    children=[
                        dmc.Title("Everything You Need to Win", order=2, ta="center"),
                        dmc.Text(
                            "A complete suite of AI-powered tools for serious sports bettors.",
                            c="dimmed",
                            ta="center",
                            size="lg",
                        ),
                    ],
                ),
                dmc.SimpleGrid(
                    cols={"base": 1, "sm": 2, "lg": 3},
                    children=[
                        dmc.Card(
                            withBorder=True,
                            radius="md",
                            p="xl",
                            style={"transition": "transform .15s"},
                            children=[
                                DashIconify(icon=f["icon"], width=30),
                                dmc.Text(f["title"], fw=700, size="lg", mb=4),
                                dmc.Text(f["desc"], c="dimmed", size="sm"),
                            ],
                        )
                        for f in FEATURES
                    ],
                ),
            ],
        ),
    )


def how_it_works_section() -> dmc.Container:
    return dmc.Container(
        size="lg",
        py="xl",
        children=dmc.Stack(
            gap="xl",
            children=[
                dmc.Stack(
                    align="center",
                    gap="sm",
                    children=[
                        dmc.Title("How It Works", order=2, ta="center"),
                        dmc.Text(
                            "From raw data to winning picks in three simple steps.",
                            c="dimmed",
                            ta="center",
                            size="lg",
                        ),
                    ],
                ),
                dmc.SimpleGrid(
                    cols={"base": 1, "sm": 3},
                    children=[
                        dmc.Card(
                            withBorder=True,
                            radius="md",
                            p="xl",
                            children=dmc.Stack(
                                gap="sm",
                                children=[
                                    dmc.Text(
                                        step["step"],
                                        size="2rem",
                                        fw=800,
                                        c="green",
                                        style={"opacity": 0.6},
                                    ),
                                    dmc.Text(step["title"], fw=700, size="lg"),
                                    dmc.Text(step["desc"], c="dimmed", size="sm"),
                                ],
                            ),
                        )
                        for step in HOW_IT_WORKS
                    ],
                ),
            ],
        ),
    )


def pricing_section() -> dmc.Container:
    return dmc.Container(
        size="lg",
        py="xl",
        children=dmc.Stack(
            gap="xl",
            children=[
                dmc.Stack(
                    align="center",
                    gap="sm",
                    children=[
                        dmc.Title("Simple, Transparent Pricing", order=2, ta="center"),
                        dmc.Text(
                            "Start free. Upgrade when you're ready to unlock the full edge.",
                            c="dimmed",
                            ta="center",
                            size="lg",
                        ),
                    ],
                ),
                dmc.SimpleGrid(
                    cols={"base": 1, "sm": 2},
                    maw=740,
                    mx="auto",
                    children=[
                        # Free plan
                        dmc.Card(
                            withBorder=True,
                            radius="md",
                            p="xl",
                            children=dmc.Stack(
                                gap="md",
                                children=[
                                    dmc.Text("Free", fw=700, size="xl"),
                                    dmc.Group(
                                        align="flex-end",
                                        gap="xs",
                                        children=[
                                            dmc.Text("$0", size="2.5rem", fw=800),
                                            dmc.Text("/month", c="dimmed", mb=6),
                                        ],
                                    ),
                                    dmc.Divider(),
                                    dmc.Stack(
                                        gap="xs",
                                        children=[
                                            dmc.Group(gap="xs", children=[DashIconify(icon="mdi:check-bold", width=16, color="#51cf66"), dmc.Text("1 free AI pick daily")]),
                                            dmc.Group(gap="xs", children=[DashIconify(icon="mdi:check-bold", width=16, color="#51cf66"), dmc.Text("Model Tracker access")]),
                                            dmc.Group(gap="xs", children=[DashIconify(icon="mdi:check-bold", width=16, color="#51cf66"), dmc.Text("Odds comparison tools")]),
                                            dmc.Group(gap="xs", children=[DashIconify(icon="mdi:check-bold", width=16, color="#51cf66"), dmc.Text("Betting calculators")]),
                                        ],
                                    ),
                                    dmc.Anchor(
                                        href="/free-pick",
                                        style={"textDecoration": "none"},
                                        children=dmc.Button(
                                            "Get Started Free →",
                                            color="green",
                                            variant="outline",
                                            fullWidth=True,
                                            radius="md",
                                        ),
                                    ),
                                ],
                            ),
                        ),
                        # Pro plan
                        dmc.Card(
                            withBorder=True,
                            radius="md",
                            p="xl",
                            style={"borderColor": "#51cf66", "borderWidth": 2},
                            children=dmc.Stack(
                                gap="md",
                                children=[
                                    dmc.Group(
                                        gap="sm",
                                        children=[
                                            dmc.Text("Pro", fw=700, size="xl"),
                                            dmc.Badge("MOST POPULAR", color="green", variant="filled", size="sm"),
                                        ],
                                    ),
                                    dmc.Group(
                                        align="flex-end",
                                        gap="xs",
                                        children=[
                                            dmc.Text("$29", size="2.5rem", fw=800, c="green"),
                                            dmc.Text("/month", c="dimmed", mb=6),
                                        ],
                                    ),
                                    dmc.Divider(),
                                    dmc.Stack(
                                        gap="xs",
                                        children=[
                                            dmc.Group(gap="xs", children=[DashIconify(icon="mdi:check-bold", width=16, color="#51cf66"), dmc.Text("50+ daily AI picks")]),
                                            dmc.Group(gap="xs", children=[DashIconify(icon="mdi:check-bold", width=16, color="#51cf66"), dmc.Text("Player props O/U predictions")]),
                                            dmc.Group(gap="xs", children=[DashIconify(icon="mdi:check-bold", width=16, color="#51cf66"), dmc.Text("Live totals tracker")]),
                                            dmc.Group(gap="xs", children=[DashIconify(icon="mdi:check-bold", width=16, color="#51cf66"), dmc.Text("Deep analytics & insights")]),
                                            dmc.Group(gap="xs", children=[DashIconify(icon="mdi:check-bold", width=16, color="#51cf66"), dmc.Text("Priority 24/7 support")]),
                                        ],
                                    ),
                                    dmc.Button(
                                        "Upgrade to Pro →",
                                        color="green",
                                        fullWidth=True,
                                        radius="md",
                                    ),
                                ],
                            ),
                        ),
                    ],
                ),
            ],
        ),
    )


def cta_section() -> dmc.Paper:
    return dmc.Paper(
        radius=0,
        style={"background": "linear-gradient(135deg, #0f2d0f 0%, #0a1a0a 100%)"},
        children=dmc.Container(
            size="md",
            py="xl",
            children=dmc.Stack(
                align="center",
                gap="lg",
                children=[
                    dmc.Title("Ready to Start Winning?", order=2, ta="center"),
                    dmc.Text(
                        "Join thousands of bettors who use Sportalytics to gain an edge every single day.",
                        c="dimmed",
                        ta="center",
                        size="lg",
                    ),
                    dmc.Group(
                        gap="md",
                        justify="center",
                        children=[
                            dmc.Anchor(
                                href="/free-pick",
                                style={"textDecoration": "none"},
                                children=dmc.Button(
                                    "Get Today's Free Pick",
                                    size="xl",
                                    color="green",
                                    radius="md",
                                    leftSection=DashIconify(icon="mdi:gift-outline", width=18),
                                ),
                            ),
                            dmc.Anchor(
                                href="/predictions",
                                style={"textDecoration": "none"},
                                children=dmc.Button(
                                    "View All Predictions",
                                    size="xl",
                                    variant="outline",
                                    color="green",
                                    radius="md",
                                ),
                            ),
                        ],
                    ),
                ],
            ),
        ),
    )


def footer_section() -> dmc.Paper:
    return dmc.Paper(
        radius=0,
        py="xl",
        children=dmc.Container(
            size="lg",
            children=dmc.Stack(
                align="center",
                gap="sm",
                children=[
                    dmc.Group(gap="xs", children=[DashIconify(icon="mdi:lightning-bolt", width=18, color="#51cf66"), dmc.Text("Sportalytics", fw=700, size="xl", c="green")]),
                    dmc.Text(
                        "AI-Powered Sports Analytics Platform",
                        c="dimmed",
                        size="sm",
                    ),
                    dmc.Group(
                        gap="lg",
                        justify="center",
                        mt="sm",
                        children=[
                            dmc.Anchor("Free Pick", href="/free-pick", size="sm", c="dimmed"),
                            dmc.Anchor("Predictions", href="/predictions", size="sm", c="dimmed"),
                            dmc.Anchor("Model Tracker", href="/model-tracker", size="sm", c="dimmed"),
                            dmc.Anchor("Marketplace", href="/marketplace", size="sm", c="dimmed"),
                            dmc.Anchor("Help", href="/help", size="sm", c="dimmed"),
                        ],
                    ),
                    dmc.Text(
                        "© 2026 Sportalytics. All rights reserved. For entertainment purposes only.",
                        c="dimmed",
                        size="xs",
                        mt="sm",
                        ta="center",
                    ),
                ],
            ),
        ),
    )


# ---------------------------------------------------------------------------
# Page layout
# ---------------------------------------------------------------------------


def layout() -> dmc.Stack:
    """Render the full landing page."""
    return dmc.Stack(
        gap=0,
        children=[
            hero_section(),
            dmc.Divider(),
            sports_section(),
            dmc.Divider(),
            features_section(),
            dmc.Divider(),
            how_it_works_section(),
            dmc.Divider(),
            pricing_section(),
            dmc.Divider(),
            cta_section(),
            dmc.Divider(),
            footer_section(),
        ],
    )

